/*
 * Darkstone Cloud API
 * REST API for the Darkstone Cloud platform: container compute, virtual machines, encrypted volumes, S3-compatible object storage, the vector database, AI inference, the DDoS-protected Cloud Gateway, billing and project management.  <a href=\"/oauth2/authorization/google\" style=\"display:inline-block;background:#4285F4;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;margin:8px 0;\">🔐 Sign in with Google</a>  After a successful login the session cookie is automatically attached to every Swagger request (same-origin). For non-browser clients, set an API key via the **Authorize** button in the top right (header `X-API-Key`, format `ds_…`). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@darkstone-entertainment.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DeployRequest;
import org.openapitools.client.model.DeployedAi;
import java.io.File;
import org.openapitools.client.model.ImportResult;
import org.openapitools.client.model.InvokeRequest;
import org.openapitools.client.model.InvokeResponse;
import org.openapitools.client.model.RenameRequest;
import org.openapitools.client.model.TrainingEntry;
import org.openapitools.client.model.TrainingPage;
import org.openapitools.client.model.TrainingRequest;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ArtificialIntelligenceApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ArtificialIntelligenceApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ArtificialIntelligenceApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addTraining
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param trainingRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addTrainingCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = trainingRequest;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}/training"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addTrainingValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling addTraining(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling addTraining(Async)");
        }

        // verify the required parameter 'trainingRequest' is set
        if (trainingRequest == null) {
            throw new ApiException("Missing the required parameter 'trainingRequest' when calling addTraining(Async)");
        }

        return addTrainingCall(projectUuid, aiUuid, trainingRequest, _callback);

    }

    /**
     * Add a training entry
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param trainingRequest  (required)
     * @return TrainingEntry
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public TrainingEntry addTraining(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest) throws ApiException {
        ApiResponse<TrainingEntry> localVarResp = addTrainingWithHttpInfo(projectUuid, aiUuid, trainingRequest);
        return localVarResp.getData();
    }

    /**
     * Add a training entry
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param trainingRequest  (required)
     * @return ApiResponse&lt;TrainingEntry&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TrainingEntry> addTrainingWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest) throws ApiException {
        okhttp3.Call localVarCall = addTrainingValidateBeforeCall(projectUuid, aiUuid, trainingRequest, null);
        Type localVarReturnType = new TypeToken<TrainingEntry>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add a training entry (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param trainingRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addTrainingAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest, final ApiCallback<TrainingEntry> _callback) throws ApiException {

        okhttp3.Call localVarCall = addTrainingValidateBeforeCall(projectUuid, aiUuid, trainingRequest, _callback);
        Type localVarReturnType = new TypeToken<TrainingEntry>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for delete5
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call delete5Call(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call delete5ValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling delete5(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling delete5(Async)");
        }

        return delete5Call(projectUuid, aiUuid, _callback);

    }

    /**
     * Delete an AI including its training data
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public void delete5(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid) throws ApiException {
        delete5WithHttpInfo(projectUuid, aiUuid);
    }

    /**
     * Delete an AI including its training data
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> delete5WithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid) throws ApiException {
        okhttp3.Call localVarCall = delete5ValidateBeforeCall(projectUuid, aiUuid, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete an AI including its training data (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call delete5Async(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = delete5ValidateBeforeCall(projectUuid, aiUuid, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteTraining
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param entryUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteTrainingCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}/training/{entryUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()))
            .replace("{" + "entryUuid" + "}", localVarApiClient.escapeString(entryUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteTrainingValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling deleteTraining(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling deleteTraining(Async)");
        }

        // verify the required parameter 'entryUuid' is set
        if (entryUuid == null) {
            throw new ApiException("Missing the required parameter 'entryUuid' when calling deleteTraining(Async)");
        }

        return deleteTrainingCall(projectUuid, aiUuid, entryUuid, _callback);

    }

    /**
     * Delete a training entry
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param entryUuid  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public void deleteTraining(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid) throws ApiException {
        deleteTrainingWithHttpInfo(projectUuid, aiUuid, entryUuid);
    }

    /**
     * Delete a training entry
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param entryUuid  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteTrainingWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid) throws ApiException {
        okhttp3.Call localVarCall = deleteTrainingValidateBeforeCall(projectUuid, aiUuid, entryUuid, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete a training entry (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param entryUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteTrainingAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteTrainingValidateBeforeCall(projectUuid, aiUuid, entryUuid, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for deploy
     * @param projectUuid  (required)
     * @param deployRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deployCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull DeployRequest deployRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = deployRequest;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deployValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull DeployRequest deployRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling deploy(Async)");
        }

        // verify the required parameter 'deployRequest' is set
        if (deployRequest == null) {
            throw new ApiException("Missing the required parameter 'deployRequest' when calling deploy(Async)");
        }

        return deployCall(projectUuid, deployRequest, _callback);

    }

    /**
     * Deploy a new AI – optionally with a base model as the starting point. If baseModelLabels is set, only training entries with those labels are inherited from the base model (platform users may not see the contents, but they choose which classification classes they want).
     * 
     * @param projectUuid  (required)
     * @param deployRequest  (required)
     * @return DeployedAi
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public DeployedAi deploy(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull DeployRequest deployRequest) throws ApiException {
        ApiResponse<DeployedAi> localVarResp = deployWithHttpInfo(projectUuid, deployRequest);
        return localVarResp.getData();
    }

    /**
     * Deploy a new AI – optionally with a base model as the starting point. If baseModelLabels is set, only training entries with those labels are inherited from the base model (platform users may not see the contents, but they choose which classification classes they want).
     * 
     * @param projectUuid  (required)
     * @param deployRequest  (required)
     * @return ApiResponse&lt;DeployedAi&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeployedAi> deployWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull DeployRequest deployRequest) throws ApiException {
        okhttp3.Call localVarCall = deployValidateBeforeCall(projectUuid, deployRequest, null);
        Type localVarReturnType = new TypeToken<DeployedAi>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Deploy a new AI – optionally with a base model as the starting point. If baseModelLabels is set, only training entries with those labels are inherited from the base model (platform users may not see the contents, but they choose which classification classes they want). (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param deployRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deployAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull DeployRequest deployRequest, final ApiCallback<DeployedAi> _callback) throws ApiException {

        okhttp3.Call localVarCall = deployValidateBeforeCall(projectUuid, deployRequest, _callback);
        Type localVarReturnType = new TypeToken<DeployedAi>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for exportTraining
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportTrainingCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}/training/export"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/csv"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call exportTrainingValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling exportTraining(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling exportTraining(Async)");
        }

        return exportTrainingCall(projectUuid, aiUuid, _callback);

    }

    /**
     * Export the training data as CSV (images are serialized as base64 in the payload field — no extra handling needed, the payload IS already base64).
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public String exportTraining(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid) throws ApiException {
        ApiResponse<String> localVarResp = exportTrainingWithHttpInfo(projectUuid, aiUuid);
        return localVarResp.getData();
    }

    /**
     * Export the training data as CSV (images are serialized as base64 in the payload field — no extra handling needed, the payload IS already base64).
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> exportTrainingWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid) throws ApiException {
        okhttp3.Call localVarCall = exportTrainingValidateBeforeCall(projectUuid, aiUuid, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Export the training data as CSV (images are serialized as base64 in the payload field — no extra handling needed, the payload IS already base64). (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportTrainingAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = exportTrainingValidateBeforeCall(projectUuid, aiUuid, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for importTraining
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _file  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call importTrainingCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull File _file, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}/training/import"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (_file != null) {
            localVarFormParams.put("file", _file);
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call importTrainingValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull File _file, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling importTraining(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling importTraining(Async)");
        }

        // verify the required parameter '_file' is set
        if (_file == null) {
            throw new ApiException("Missing the required parameter '_file' when calling importTraining(Async)");
        }

        return importTrainingCall(projectUuid, aiUuid, _file, _callback);

    }

    /**
     * Import training data from a CSV. Expected format: a &#39;label,payload&#39; header row. For image classifiers, payload contains the base64-encoded byte stream of the image file.
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _file  (required)
     * @return ImportResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ImportResult importTraining(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull File _file) throws ApiException {
        ApiResponse<ImportResult> localVarResp = importTrainingWithHttpInfo(projectUuid, aiUuid, _file);
        return localVarResp.getData();
    }

    /**
     * Import training data from a CSV. Expected format: a &#39;label,payload&#39; header row. For image classifiers, payload contains the base64-encoded byte stream of the image file.
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _file  (required)
     * @return ApiResponse&lt;ImportResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ImportResult> importTrainingWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull File _file) throws ApiException {
        okhttp3.Call localVarCall = importTrainingValidateBeforeCall(projectUuid, aiUuid, _file, null);
        Type localVarReturnType = new TypeToken<ImportResult>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Import training data from a CSV. Expected format: a &#39;label,payload&#39; header row. For image classifiers, payload contains the base64-encoded byte stream of the image file. (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _file  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call importTrainingAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull File _file, final ApiCallback<ImportResult> _callback) throws ApiException {

        okhttp3.Call localVarCall = importTrainingValidateBeforeCall(projectUuid, aiUuid, _file, _callback);
        Type localVarReturnType = new TypeToken<ImportResult>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for invoke
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param invokeRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call invokeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull InvokeRequest invokeRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = invokeRequest;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}/invoke"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call invokeValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull InvokeRequest invokeRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling invoke(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling invoke(Async)");
        }

        // verify the required parameter 'invokeRequest' is set
        if (invokeRequest == null) {
            throw new ApiException("Missing the required parameter 'invokeRequest' when calling invoke(Async)");
        }

        return invokeCall(projectUuid, aiUuid, invokeRequest, _callback);

    }

    /**
     * Test an AI from the dashboard (rate-limited). Production calls go through the cloud gateways.
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param invokeRequest  (required)
     * @return InvokeResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public InvokeResponse invoke(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull InvokeRequest invokeRequest) throws ApiException {
        ApiResponse<InvokeResponse> localVarResp = invokeWithHttpInfo(projectUuid, aiUuid, invokeRequest);
        return localVarResp.getData();
    }

    /**
     * Test an AI from the dashboard (rate-limited). Production calls go through the cloud gateways.
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param invokeRequest  (required)
     * @return ApiResponse&lt;InvokeResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InvokeResponse> invokeWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull InvokeRequest invokeRequest) throws ApiException {
        okhttp3.Call localVarCall = invokeValidateBeforeCall(projectUuid, aiUuid, invokeRequest, null);
        Type localVarReturnType = new TypeToken<InvokeResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Test an AI from the dashboard (rate-limited). Production calls go through the cloud gateways. (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param invokeRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call invokeAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull InvokeRequest invokeRequest, final ApiCallback<InvokeResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = invokeValidateBeforeCall(projectUuid, aiUuid, invokeRequest, _callback);
        Type localVarReturnType = new TypeToken<InvokeResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for list14
     * @param projectUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call list14Call(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call list14ValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling list14(Async)");
        }

        return list14Call(projectUuid, _callback);

    }

    /**
     * All AIs deployed in the project
     * 
     * @param projectUuid  (required)
     * @return List&lt;DeployedAi&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<DeployedAi> list14(@javax.annotation.Nonnull UUID projectUuid) throws ApiException {
        ApiResponse<List<DeployedAi>> localVarResp = list14WithHttpInfo(projectUuid);
        return localVarResp.getData();
    }

    /**
     * All AIs deployed in the project
     * 
     * @param projectUuid  (required)
     * @return ApiResponse&lt;List&lt;DeployedAi&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<DeployedAi>> list14WithHttpInfo(@javax.annotation.Nonnull UUID projectUuid) throws ApiException {
        okhttp3.Call localVarCall = list14ValidateBeforeCall(projectUuid, null);
        Type localVarReturnType = new TypeToken<List<DeployedAi>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * All AIs deployed in the project (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call list14Async(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback<List<DeployedAi>> _callback) throws ApiException {

        okhttp3.Call localVarCall = list14ValidateBeforeCall(projectUuid, _callback);
        Type localVarReturnType = new TypeToken<List<DeployedAi>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listTraining
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listTrainingCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}/training"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listTrainingValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling listTraining(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling listTraining(Async)");
        }

        return listTrainingCall(projectUuid, aiUuid, page, size, _callback);

    }

    /**
     * List the training data of the AI — paginated (default 10/page)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return TrainingPage
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public TrainingPage listTraining(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size) throws ApiException {
        ApiResponse<TrainingPage> localVarResp = listTrainingWithHttpInfo(projectUuid, aiUuid, page, size);
        return localVarResp.getData();
    }

    /**
     * List the training data of the AI — paginated (default 10/page)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return ApiResponse&lt;TrainingPage&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TrainingPage> listTrainingWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size) throws ApiException {
        okhttp3.Call localVarCall = listTrainingValidateBeforeCall(projectUuid, aiUuid, page, size, null);
        Type localVarReturnType = new TypeToken<TrainingPage>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List the training data of the AI — paginated (default 10/page) (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listTrainingAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, final ApiCallback<TrainingPage> _callback) throws ApiException {

        okhttp3.Call localVarCall = listTrainingValidateBeforeCall(projectUuid, aiUuid, page, size, _callback);
        Type localVarReturnType = new TypeToken<TrainingPage>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listTrainingLabels
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listTrainingLabelsCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}/training/labels"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listTrainingLabelsValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling listTrainingLabels(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling listTrainingLabels(Async)");
        }

        return listTrainingLabelsCall(projectUuid, aiUuid, _callback);

    }

    /**
     * Distinct labels of the existing training data
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @return List&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<String> listTrainingLabels(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid) throws ApiException {
        ApiResponse<List<String>> localVarResp = listTrainingLabelsWithHttpInfo(projectUuid, aiUuid);
        return localVarResp.getData();
    }

    /**
     * Distinct labels of the existing training data
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @return ApiResponse&lt;List&lt;String&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<String>> listTrainingLabelsWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid) throws ApiException {
        okhttp3.Call localVarCall = listTrainingLabelsValidateBeforeCall(projectUuid, aiUuid, null);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Distinct labels of the existing training data (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listTrainingLabelsAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, final ApiCallback<List<String>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listTrainingLabelsValidateBeforeCall(projectUuid, aiUuid, _callback);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for rename4
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param renameRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call rename4Call(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull RenameRequest renameRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = renameRequest;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call rename4ValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull RenameRequest renameRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling rename4(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling rename4(Async)");
        }

        // verify the required parameter 'renameRequest' is set
        if (renameRequest == null) {
            throw new ApiException("Missing the required parameter 'renameRequest' when calling rename4(Async)");
        }

        return rename4Call(projectUuid, aiUuid, renameRequest, _callback);

    }

    /**
     * Rename an AI
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param renameRequest  (required)
     * @return DeployedAi
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public DeployedAi rename4(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull RenameRequest renameRequest) throws ApiException {
        ApiResponse<DeployedAi> localVarResp = rename4WithHttpInfo(projectUuid, aiUuid, renameRequest);
        return localVarResp.getData();
    }

    /**
     * Rename an AI
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param renameRequest  (required)
     * @return ApiResponse&lt;DeployedAi&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeployedAi> rename4WithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull RenameRequest renameRequest) throws ApiException {
        okhttp3.Call localVarCall = rename4ValidateBeforeCall(projectUuid, aiUuid, renameRequest, null);
        Type localVarReturnType = new TypeToken<DeployedAi>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Rename an AI (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param renameRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call rename4Async(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull RenameRequest renameRequest, final ApiCallback<DeployedAi> _callback) throws ApiException {

        okhttp3.Call localVarCall = rename4ValidateBeforeCall(projectUuid, aiUuid, renameRequest, _callback);
        Type localVarReturnType = new TypeToken<DeployedAi>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateTraining
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param entryUuid  (required)
     * @param trainingRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTrainingCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = trainingRequest;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/ai/{aiUuid}/training/{entryUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "aiUuid" + "}", localVarApiClient.escapeString(aiUuid.toString()))
            .replace("{" + "entryUuid" + "}", localVarApiClient.escapeString(entryUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateTrainingValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling updateTraining(Async)");
        }

        // verify the required parameter 'aiUuid' is set
        if (aiUuid == null) {
            throw new ApiException("Missing the required parameter 'aiUuid' when calling updateTraining(Async)");
        }

        // verify the required parameter 'entryUuid' is set
        if (entryUuid == null) {
            throw new ApiException("Missing the required parameter 'entryUuid' when calling updateTraining(Async)");
        }

        // verify the required parameter 'trainingRequest' is set
        if (trainingRequest == null) {
            throw new ApiException("Missing the required parameter 'trainingRequest' when calling updateTraining(Async)");
        }

        return updateTrainingCall(projectUuid, aiUuid, entryUuid, trainingRequest, _callback);

    }

    /**
     * Update a training entry
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param entryUuid  (required)
     * @param trainingRequest  (required)
     * @return TrainingEntry
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public TrainingEntry updateTraining(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest) throws ApiException {
        ApiResponse<TrainingEntry> localVarResp = updateTrainingWithHttpInfo(projectUuid, aiUuid, entryUuid, trainingRequest);
        return localVarResp.getData();
    }

    /**
     * Update a training entry
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param entryUuid  (required)
     * @param trainingRequest  (required)
     * @return ApiResponse&lt;TrainingEntry&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TrainingEntry> updateTrainingWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest) throws ApiException {
        okhttp3.Call localVarCall = updateTrainingValidateBeforeCall(projectUuid, aiUuid, entryUuid, trainingRequest, null);
        Type localVarReturnType = new TypeToken<TrainingEntry>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a training entry (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param aiUuid  (required)
     * @param entryUuid  (required)
     * @param trainingRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTrainingAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID aiUuid, @javax.annotation.Nonnull UUID entryUuid, @javax.annotation.Nonnull TrainingRequest trainingRequest, final ApiCallback<TrainingEntry> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateTrainingValidateBeforeCall(projectUuid, aiUuid, entryUuid, trainingRequest, _callback);
        Type localVarReturnType = new TypeToken<TrainingEntry>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
