/*
 * Darkstone Cloud API
 * REST API for the Darkstone Cloud platform: container compute, virtual machines, encrypted volumes, S3-compatible object storage, the vector database, AI inference, the DDoS-protected Cloud Gateway, billing and project management.  <a href=\"/oauth2/authorization/google\" style=\"display:inline-block;background:#4285F4;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;margin:8px 0;\">🔐 Sign in with Google</a>  After a successful login the session cookie is automatically attached to every Swagger request (same-origin). For non-browser clients, set an API key via the **Authorize** button in the top right (header `X-API-Key`, format `ds_…`). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@darkstone-entertainment.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.CreateGatewayRequestV2;
import org.openapitools.client.model.CreateRouteRequestV2;
import java.io.File;
import org.openapitools.client.model.GatewayDtoV2;
import org.openapitools.client.model.GatewayLiveDto;
import org.openapitools.client.model.GatewayStatsDto;
import org.openapitools.client.model.RenameGatewayRequestV2;
import org.openapitools.client.model.RouteDtoV2;
import java.util.UUID;
import org.openapitools.client.model.UpdateRouteRequestV2;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CloudGatewaysV2Api {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CloudGatewaysV2Api() {
        this(Configuration.getDefaultApiClient());
    }

    public CloudGatewaysV2Api(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for callList
     * @param projectUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call callListCall(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call callListValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling callList(Async)");
        }

        return callListCall(projectUuid, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @return List&lt;GatewayDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<GatewayDtoV2> callList(@javax.annotation.Nonnull UUID projectUuid) throws ApiException {
        ApiResponse<List<GatewayDtoV2>> localVarResp = callListWithHttpInfo(projectUuid);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @return ApiResponse&lt;List&lt;GatewayDtoV2&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<GatewayDtoV2>> callListWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid) throws ApiException {
        okhttp3.Call localVarCall = callListValidateBeforeCall(projectUuid, null);
        Type localVarReturnType = new TypeToken<List<GatewayDtoV2>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call callListAsync(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback<List<GatewayDtoV2>> _callback) throws ApiException {

        okhttp3.Call localVarCall = callListValidateBeforeCall(projectUuid, _callback);
        Type localVarReturnType = new TypeToken<List<GatewayDtoV2>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for create
     * @param projectUuid  (required)
     * @param createGatewayRequestV2  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateGatewayRequestV2 createGatewayRequestV2, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createGatewayRequestV2;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateGatewayRequestV2 createGatewayRequestV2, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling create(Async)");
        }

        // verify the required parameter 'createGatewayRequestV2' is set
        if (createGatewayRequestV2 == null) {
            throw new ApiException("Missing the required parameter 'createGatewayRequestV2' when calling create(Async)");
        }

        return createCall(projectUuid, createGatewayRequestV2, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param createGatewayRequestV2  (required)
     * @return GatewayDtoV2
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GatewayDtoV2 create(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateGatewayRequestV2 createGatewayRequestV2) throws ApiException {
        ApiResponse<GatewayDtoV2> localVarResp = createWithHttpInfo(projectUuid, createGatewayRequestV2);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param createGatewayRequestV2  (required)
     * @return ApiResponse&lt;GatewayDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GatewayDtoV2> createWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateGatewayRequestV2 createGatewayRequestV2) throws ApiException {
        okhttp3.Call localVarCall = createValidateBeforeCall(projectUuid, createGatewayRequestV2, null);
        Type localVarReturnType = new TypeToken<GatewayDtoV2>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param createGatewayRequestV2  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateGatewayRequestV2 createGatewayRequestV2, final ApiCallback<GatewayDtoV2> _callback) throws ApiException {

        okhttp3.Call localVarCall = createValidateBeforeCall(projectUuid, createGatewayRequestV2, _callback);
        Type localVarReturnType = new TypeToken<GatewayDtoV2>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createRoute
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param createRouteRequestV2  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRouteCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull CreateRouteRequestV2 createRouteRequestV2, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createRouteRequestV2;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}/routes"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createRouteValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull CreateRouteRequestV2 createRouteRequestV2, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling createRoute(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling createRoute(Async)");
        }

        // verify the required parameter 'createRouteRequestV2' is set
        if (createRouteRequestV2 == null) {
            throw new ApiException("Missing the required parameter 'createRouteRequestV2' when calling createRoute(Async)");
        }

        return createRouteCall(projectUuid, gatewayUuid, createRouteRequestV2, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param createRouteRequestV2  (required)
     * @return RouteDtoV2
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public RouteDtoV2 createRoute(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull CreateRouteRequestV2 createRouteRequestV2) throws ApiException {
        ApiResponse<RouteDtoV2> localVarResp = createRouteWithHttpInfo(projectUuid, gatewayUuid, createRouteRequestV2);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param createRouteRequestV2  (required)
     * @return ApiResponse&lt;RouteDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RouteDtoV2> createRouteWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull CreateRouteRequestV2 createRouteRequestV2) throws ApiException {
        okhttp3.Call localVarCall = createRouteValidateBeforeCall(projectUuid, gatewayUuid, createRouteRequestV2, null);
        Type localVarReturnType = new TypeToken<RouteDtoV2>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param createRouteRequestV2  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRouteAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull CreateRouteRequestV2 createRouteRequestV2, final ApiCallback<RouteDtoV2> _callback) throws ApiException {

        okhttp3.Call localVarCall = createRouteValidateBeforeCall(projectUuid, gatewayUuid, createRouteRequestV2, _callback);
        Type localVarReturnType = new TypeToken<RouteDtoV2>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for delete
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling delete(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling delete(Async)");
        }

        return deleteCall(projectUuid, gatewayUuid, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public void delete(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        deleteWithHttpInfo(projectUuid, gatewayUuid);
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        okhttp3.Call localVarCall = deleteValidateBeforeCall(projectUuid, gatewayUuid, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteValidateBeforeCall(projectUuid, gatewayUuid, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteRoute
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteRouteCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}/routes/{routeUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()))
            .replace("{" + "routeUuid" + "}", localVarApiClient.escapeString(routeUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteRouteValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling deleteRoute(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling deleteRoute(Async)");
        }

        // verify the required parameter 'routeUuid' is set
        if (routeUuid == null) {
            throw new ApiException("Missing the required parameter 'routeUuid' when calling deleteRoute(Async)");
        }

        return deleteRouteCall(projectUuid, gatewayUuid, routeUuid, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public void deleteRoute(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid) throws ApiException {
        deleteRouteWithHttpInfo(projectUuid, gatewayUuid, routeUuid);
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteRouteWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid) throws ApiException {
        okhttp3.Call localVarCall = deleteRouteValidateBeforeCall(projectUuid, gatewayUuid, routeUuid, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteRouteAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteRouteValidateBeforeCall(projectUuid, gatewayUuid, routeUuid, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for get
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling get(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling get(Async)");
        }

        return getCall(projectUuid, gatewayUuid, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return GatewayDtoV2
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GatewayDtoV2 get(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        ApiResponse<GatewayDtoV2> localVarResp = getWithHttpInfo(projectUuid, gatewayUuid);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return ApiResponse&lt;GatewayDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GatewayDtoV2> getWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        okhttp3.Call localVarCall = getValidateBeforeCall(projectUuid, gatewayUuid, null);
        Type localVarReturnType = new TypeToken<GatewayDtoV2>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback<GatewayDtoV2> _callback) throws ApiException {

        okhttp3.Call localVarCall = getValidateBeforeCall(projectUuid, gatewayUuid, _callback);
        Type localVarReturnType = new TypeToken<GatewayDtoV2>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listRoutes
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listRoutesCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}/routes"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listRoutesValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling listRoutes(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling listRoutes(Async)");
        }

        return listRoutesCall(projectUuid, gatewayUuid, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return List&lt;RouteDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<RouteDtoV2> listRoutes(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        ApiResponse<List<RouteDtoV2>> localVarResp = listRoutesWithHttpInfo(projectUuid, gatewayUuid);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return ApiResponse&lt;List&lt;RouteDtoV2&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<RouteDtoV2>> listRoutesWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        okhttp3.Call localVarCall = listRoutesValidateBeforeCall(projectUuid, gatewayUuid, null);
        Type localVarReturnType = new TypeToken<List<RouteDtoV2>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listRoutesAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback<List<RouteDtoV2>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listRoutesValidateBeforeCall(projectUuid, gatewayUuid, _callback);
        Type localVarReturnType = new TypeToken<List<RouteDtoV2>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for rename
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param renameGatewayRequestV2  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call renameCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull RenameGatewayRequestV2 renameGatewayRequestV2, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = renameGatewayRequestV2;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call renameValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull RenameGatewayRequestV2 renameGatewayRequestV2, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling rename(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling rename(Async)");
        }

        // verify the required parameter 'renameGatewayRequestV2' is set
        if (renameGatewayRequestV2 == null) {
            throw new ApiException("Missing the required parameter 'renameGatewayRequestV2' when calling rename(Async)");
        }

        return renameCall(projectUuid, gatewayUuid, renameGatewayRequestV2, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param renameGatewayRequestV2  (required)
     * @return GatewayDtoV2
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GatewayDtoV2 rename(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull RenameGatewayRequestV2 renameGatewayRequestV2) throws ApiException {
        ApiResponse<GatewayDtoV2> localVarResp = renameWithHttpInfo(projectUuid, gatewayUuid, renameGatewayRequestV2);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param renameGatewayRequestV2  (required)
     * @return ApiResponse&lt;GatewayDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GatewayDtoV2> renameWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull RenameGatewayRequestV2 renameGatewayRequestV2) throws ApiException {
        okhttp3.Call localVarCall = renameValidateBeforeCall(projectUuid, gatewayUuid, renameGatewayRequestV2, null);
        Type localVarReturnType = new TypeToken<GatewayDtoV2>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param renameGatewayRequestV2  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call renameAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull RenameGatewayRequestV2 renameGatewayRequestV2, final ApiCallback<GatewayDtoV2> _callback) throws ApiException {

        okhttp3.Call localVarCall = renameValidateBeforeCall(projectUuid, gatewayUuid, renameGatewayRequestV2, _callback);
        Type localVarReturnType = new TypeToken<GatewayDtoV2>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for stats
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call statsCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}/stats"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call statsValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling stats(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling stats(Async)");
        }

        return statsCall(projectUuid, gatewayUuid, _callback);

    }

    /**
     * Live statistics: per-minute traffic (60-minute window) + total + route count
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return GatewayStatsDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GatewayStatsDto stats(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        ApiResponse<GatewayStatsDto> localVarResp = statsWithHttpInfo(projectUuid, gatewayUuid);
        return localVarResp.getData();
    }

    /**
     * Live statistics: per-minute traffic (60-minute window) + total + route count
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return ApiResponse&lt;GatewayStatsDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GatewayStatsDto> statsWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        okhttp3.Call localVarCall = statsValidateBeforeCall(projectUuid, gatewayUuid, null);
        Type localVarReturnType = new TypeToken<GatewayStatsDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Live statistics: per-minute traffic (60-minute window) + total + route count (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call statsAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback<GatewayStatsDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = statsValidateBeforeCall(projectUuid, gatewayUuid, _callback);
        Type localVarReturnType = new TypeToken<GatewayStatsDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for statsLive
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call statsLiveCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}/stats/live"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call statsLiveValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling statsLive(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling statsLive(Async)");
        }

        return statsLiveCall(projectUuid, gatewayUuid, _callback);

    }

    /**
     * Live counter: cumulative all-time traffic (O(1) read, for 2s polling)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return GatewayLiveDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public GatewayLiveDto statsLive(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        ApiResponse<GatewayLiveDto> localVarResp = statsLiveWithHttpInfo(projectUuid, gatewayUuid);
        return localVarResp.getData();
    }

    /**
     * Live counter: cumulative all-time traffic (O(1) read, for 2s polling)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @return ApiResponse&lt;GatewayLiveDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GatewayLiveDto> statsLiveWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid) throws ApiException {
        okhttp3.Call localVarCall = statsLiveValidateBeforeCall(projectUuid, gatewayUuid, null);
        Type localVarReturnType = new TypeToken<GatewayLiveDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Live counter: cumulative all-time traffic (O(1) read, for 2s polling) (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call statsLiveAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, final ApiCallback<GatewayLiveDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = statsLiveValidateBeforeCall(projectUuid, gatewayUuid, _callback);
        Type localVarReturnType = new TypeToken<GatewayLiveDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateRoute
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param updateRouteRequestV2  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRouteCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull UpdateRouteRequestV2 updateRouteRequestV2, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateRouteRequestV2;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}/routes/{routeUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()))
            .replace("{" + "routeUuid" + "}", localVarApiClient.escapeString(routeUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateRouteValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull UpdateRouteRequestV2 updateRouteRequestV2, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling updateRoute(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling updateRoute(Async)");
        }

        // verify the required parameter 'routeUuid' is set
        if (routeUuid == null) {
            throw new ApiException("Missing the required parameter 'routeUuid' when calling updateRoute(Async)");
        }

        // verify the required parameter 'updateRouteRequestV2' is set
        if (updateRouteRequestV2 == null) {
            throw new ApiException("Missing the required parameter 'updateRouteRequestV2' when calling updateRoute(Async)");
        }

        return updateRouteCall(projectUuid, gatewayUuid, routeUuid, updateRouteRequestV2, _callback);

    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param updateRouteRequestV2  (required)
     * @return RouteDtoV2
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public RouteDtoV2 updateRoute(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull UpdateRouteRequestV2 updateRouteRequestV2) throws ApiException {
        ApiResponse<RouteDtoV2> localVarResp = updateRouteWithHttpInfo(projectUuid, gatewayUuid, routeUuid, updateRouteRequestV2);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param updateRouteRequestV2  (required)
     * @return ApiResponse&lt;RouteDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RouteDtoV2> updateRouteWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull UpdateRouteRequestV2 updateRouteRequestV2) throws ApiException {
        okhttp3.Call localVarCall = updateRouteValidateBeforeCall(projectUuid, gatewayUuid, routeUuid, updateRouteRequestV2, null);
        Type localVarReturnType = new TypeToken<RouteDtoV2>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param updateRouteRequestV2  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRouteAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull UpdateRouteRequestV2 updateRouteRequestV2, final ApiCallback<RouteDtoV2> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateRouteValidateBeforeCall(projectUuid, gatewayUuid, routeUuid, updateRouteRequestV2, _callback);
        Type localVarReturnType = new TypeToken<RouteDtoV2>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for uploadCertificate
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param cert  (required)
     * @param key  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadCertificateCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull File cert, @javax.annotation.Nonnull File key, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}/routes/{routeUuid}/certificate"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()))
            .replace("{" + "routeUuid" + "}", localVarApiClient.escapeString(routeUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cert != null) {
            localVarFormParams.put("cert", cert);
        }

        if (key != null) {
            localVarFormParams.put("key", key);
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call uploadCertificateValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull File cert, @javax.annotation.Nonnull File key, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling uploadCertificate(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling uploadCertificate(Async)");
        }

        // verify the required parameter 'routeUuid' is set
        if (routeUuid == null) {
            throw new ApiException("Missing the required parameter 'routeUuid' when calling uploadCertificate(Async)");
        }

        // verify the required parameter 'cert' is set
        if (cert == null) {
            throw new ApiException("Missing the required parameter 'cert' when calling uploadCertificate(Async)");
        }

        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling uploadCertificate(Async)");
        }

        return uploadCertificateCall(projectUuid, gatewayUuid, routeUuid, cert, key, _callback);

    }

    /**
     * Upload/replace your own TLS certificate (CUSTOM mode, no auto-renewal)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param cert  (required)
     * @param key  (required)
     * @return RouteDtoV2
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public RouteDtoV2 uploadCertificate(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull File cert, @javax.annotation.Nonnull File key) throws ApiException {
        ApiResponse<RouteDtoV2> localVarResp = uploadCertificateWithHttpInfo(projectUuid, gatewayUuid, routeUuid, cert, key);
        return localVarResp.getData();
    }

    /**
     * Upload/replace your own TLS certificate (CUSTOM mode, no auto-renewal)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param cert  (required)
     * @param key  (required)
     * @return ApiResponse&lt;RouteDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RouteDtoV2> uploadCertificateWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull File cert, @javax.annotation.Nonnull File key) throws ApiException {
        okhttp3.Call localVarCall = uploadCertificateValidateBeforeCall(projectUuid, gatewayUuid, routeUuid, cert, key, null);
        Type localVarReturnType = new TypeToken<RouteDtoV2>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Upload/replace your own TLS certificate (CUSTOM mode, no auto-renewal) (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param cert  (required)
     * @param key  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadCertificateAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, @javax.annotation.Nonnull File cert, @javax.annotation.Nonnull File key, final ApiCallback<RouteDtoV2> _callback) throws ApiException {

        okhttp3.Call localVarCall = uploadCertificateValidateBeforeCall(projectUuid, gatewayUuid, routeUuid, cert, key, _callback);
        Type localVarReturnType = new TypeToken<RouteDtoV2>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for useManagedCertificate
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call useManagedCertificateCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/projects/{projectUuid}/cloudgates/{gatewayUuid}/routes/{routeUuid}/certificate/managed"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "gatewayUuid" + "}", localVarApiClient.escapeString(gatewayUuid.toString()))
            .replace("{" + "routeUuid" + "}", localVarApiClient.escapeString(routeUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call useManagedCertificateValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling useManagedCertificate(Async)");
        }

        // verify the required parameter 'gatewayUuid' is set
        if (gatewayUuid == null) {
            throw new ApiException("Missing the required parameter 'gatewayUuid' when calling useManagedCertificate(Async)");
        }

        // verify the required parameter 'routeUuid' is set
        if (routeUuid == null) {
            throw new ApiException("Missing the required parameter 'routeUuid' when calling useManagedCertificate(Async)");
        }

        return useManagedCertificateCall(projectUuid, gatewayUuid, routeUuid, _callback);

    }

    /**
     * Switch back to a managed Let&#39;s Encrypt certificate (with auto-renewal)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @return RouteDtoV2
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public RouteDtoV2 useManagedCertificate(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid) throws ApiException {
        ApiResponse<RouteDtoV2> localVarResp = useManagedCertificateWithHttpInfo(projectUuid, gatewayUuid, routeUuid);
        return localVarResp.getData();
    }

    /**
     * Switch back to a managed Let&#39;s Encrypt certificate (with auto-renewal)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @return ApiResponse&lt;RouteDtoV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RouteDtoV2> useManagedCertificateWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid) throws ApiException {
        okhttp3.Call localVarCall = useManagedCertificateValidateBeforeCall(projectUuid, gatewayUuid, routeUuid, null);
        Type localVarReturnType = new TypeToken<RouteDtoV2>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Switch back to a managed Let&#39;s Encrypt certificate (with auto-renewal) (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param gatewayUuid  (required)
     * @param routeUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call useManagedCertificateAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID gatewayUuid, @javax.annotation.Nonnull UUID routeUuid, final ApiCallback<RouteDtoV2> _callback) throws ApiException {

        okhttp3.Call localVarCall = useManagedCertificateValidateBeforeCall(projectUuid, gatewayUuid, routeUuid, _callback);
        Type localVarReturnType = new TypeToken<RouteDtoV2>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
