/*
 * Darkstone Cloud API
 * REST API for the Darkstone Cloud platform: container compute, virtual machines, encrypted volumes, S3-compatible object storage, the vector database, AI inference, the DDoS-protected Cloud Gateway, billing and project management.  <a href=\"/oauth2/authorization/google\" style=\"display:inline-block;background:#4285F4;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;margin:8px 0;\">🔐 Sign in with Google</a>  After a successful login the session cookie is automatically attached to every Swagger request (same-origin). For non-browser clients, set an API key via the **Authorize** button in the top right (header `X-API-Key`, format `ds_…`). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@darkstone-entertainment.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ChatRequest;
import org.openapitools.client.model.ChatResponse;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DataPlaneAiApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DataPlaneAiApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DataPlaneAiApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for chatCompletion
     * @param xCloudgateTargetResource  (required)
     * @param chatRequest  (required)
     * @param xCloudgateRoute  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call chatCompletionCall(@javax.annotation.Nonnull UUID xCloudgateTargetResource, @javax.annotation.Nonnull ChatRequest chatRequest, @javax.annotation.Nullable String xCloudgateRoute, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = chatRequest;

        // create path and map variables
        String localVarPath = "/data/v1/ai/v1/chat/completions";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xCloudgateTargetResource != null) {
            localVarHeaderParams.put("X-Cloudgate-Target-Resource", localVarApiClient.parameterToString(xCloudgateTargetResource));
        }


        if (xCloudgateRoute != null) {
            localVarHeaderParams.put("X-Cloudgate-Route", localVarApiClient.parameterToString(xCloudgateRoute));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call chatCompletionValidateBeforeCall(@javax.annotation.Nonnull UUID xCloudgateTargetResource, @javax.annotation.Nonnull ChatRequest chatRequest, @javax.annotation.Nullable String xCloudgateRoute, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xCloudgateTargetResource' is set
        if (xCloudgateTargetResource == null) {
            throw new ApiException("Missing the required parameter 'xCloudgateTargetResource' when calling chatCompletion(Async)");
        }

        // verify the required parameter 'chatRequest' is set
        if (chatRequest == null) {
            throw new ApiException("Missing the required parameter 'chatRequest' when calling chatCompletion(Async)");
        }

        return chatCompletionCall(xCloudgateTargetResource, chatRequest, xCloudgateRoute, _callback);

    }

    /**
     * Classification (OpenAI Chat Completions compatible)
     * 
     * @param xCloudgateTargetResource  (required)
     * @param chatRequest  (required)
     * @param xCloudgateRoute  (optional)
     * @return ChatResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ChatResponse chatCompletion(@javax.annotation.Nonnull UUID xCloudgateTargetResource, @javax.annotation.Nonnull ChatRequest chatRequest, @javax.annotation.Nullable String xCloudgateRoute) throws ApiException {
        ApiResponse<ChatResponse> localVarResp = chatCompletionWithHttpInfo(xCloudgateTargetResource, chatRequest, xCloudgateRoute);
        return localVarResp.getData();
    }

    /**
     * Classification (OpenAI Chat Completions compatible)
     * 
     * @param xCloudgateTargetResource  (required)
     * @param chatRequest  (required)
     * @param xCloudgateRoute  (optional)
     * @return ApiResponse&lt;ChatResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ChatResponse> chatCompletionWithHttpInfo(@javax.annotation.Nonnull UUID xCloudgateTargetResource, @javax.annotation.Nonnull ChatRequest chatRequest, @javax.annotation.Nullable String xCloudgateRoute) throws ApiException {
        okhttp3.Call localVarCall = chatCompletionValidateBeforeCall(xCloudgateTargetResource, chatRequest, xCloudgateRoute, null);
        Type localVarReturnType = new TypeToken<ChatResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Classification (OpenAI Chat Completions compatible) (asynchronously)
     * 
     * @param xCloudgateTargetResource  (required)
     * @param chatRequest  (required)
     * @param xCloudgateRoute  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call chatCompletionAsync(@javax.annotation.Nonnull UUID xCloudgateTargetResource, @javax.annotation.Nonnull ChatRequest chatRequest, @javax.annotation.Nullable String xCloudgateRoute, final ApiCallback<ChatResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = chatCompletionValidateBeforeCall(xCloudgateTargetResource, chatRequest, xCloudgateRoute, _callback);
        Type localVarReturnType = new TypeToken<ChatResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
