/*
 * Darkstone Cloud API
 * REST API for the Darkstone Cloud platform: container compute, virtual machines, encrypted volumes, S3-compatible object storage, the vector database, AI inference, the DDoS-protected Cloud Gateway, billing and project management.  <a href=\"/oauth2/authorization/google\" style=\"display:inline-block;background:#4285F4;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;margin:8px 0;\">🔐 Sign in with Google</a>  After a successful login the session cookie is automatically attached to every Swagger request (same-origin). For non-browser clients, set an API key via the **Authorize** button in the top right (header `X-API-Key`, format `ds_…`). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@darkstone-entertainment.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.AttachRequest;
import org.openapitools.client.model.AttachmentDto;
import org.openapitools.client.model.CreateRequest;
import org.openapitools.client.model.TenantNetworkDto;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TenantNetworksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TenantNetworksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TenantNetworksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for attach
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param attachRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call attachCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull AttachRequest attachRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = attachRequest;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/networks/{networkUuid}/attachments"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "networkUuid" + "}", localVarApiClient.escapeString(networkUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call attachValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull AttachRequest attachRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling attach(Async)");
        }

        // verify the required parameter 'networkUuid' is set
        if (networkUuid == null) {
            throw new ApiException("Missing the required parameter 'networkUuid' when calling attach(Async)");
        }

        // verify the required parameter 'attachRequest' is set
        if (attachRequest == null) {
            throw new ApiException("Missing the required parameter 'attachRequest' when calling attach(Async)");
        }

        return attachCall(projectUuid, networkUuid, attachRequest, _callback);

    }

    /**
     * Eine VM in das Netzwerk haengen (MOVE-Semantik)
     * Eine VM ist in HOECHSTENS einem Netz. Haengt die VM schon in einem anderen Netz, wird sie dorthin VERSCHOBEN (erst aus dem alten getrennt, dann ins neue gehaengt) — danach ist sie in genau diesem Netz. Idempotent, wenn sie schon hier haengt. Doppelter IDOR-Guard (Netz UND VM muessen zum Pfad-Projekt gehoeren). KubeVirt uebernimmt das geaenderte Secondary-Interface erst beim VMI-Neustart → restartRequired&#x3D;true signalisiert &#39;pending restart&#39;.
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param attachRequest  (required)
     * @return AttachmentDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public AttachmentDto attach(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull AttachRequest attachRequest) throws ApiException {
        ApiResponse<AttachmentDto> localVarResp = attachWithHttpInfo(projectUuid, networkUuid, attachRequest);
        return localVarResp.getData();
    }

    /**
     * Eine VM in das Netzwerk haengen (MOVE-Semantik)
     * Eine VM ist in HOECHSTENS einem Netz. Haengt die VM schon in einem anderen Netz, wird sie dorthin VERSCHOBEN (erst aus dem alten getrennt, dann ins neue gehaengt) — danach ist sie in genau diesem Netz. Idempotent, wenn sie schon hier haengt. Doppelter IDOR-Guard (Netz UND VM muessen zum Pfad-Projekt gehoeren). KubeVirt uebernimmt das geaenderte Secondary-Interface erst beim VMI-Neustart → restartRequired&#x3D;true signalisiert &#39;pending restart&#39;.
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param attachRequest  (required)
     * @return ApiResponse&lt;AttachmentDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AttachmentDto> attachWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull AttachRequest attachRequest) throws ApiException {
        okhttp3.Call localVarCall = attachValidateBeforeCall(projectUuid, networkUuid, attachRequest, null);
        Type localVarReturnType = new TypeToken<AttachmentDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Eine VM in das Netzwerk haengen (MOVE-Semantik) (asynchronously)
     * Eine VM ist in HOECHSTENS einem Netz. Haengt die VM schon in einem anderen Netz, wird sie dorthin VERSCHOBEN (erst aus dem alten getrennt, dann ins neue gehaengt) — danach ist sie in genau diesem Netz. Idempotent, wenn sie schon hier haengt. Doppelter IDOR-Guard (Netz UND VM muessen zum Pfad-Projekt gehoeren). KubeVirt uebernimmt das geaenderte Secondary-Interface erst beim VMI-Neustart → restartRequired&#x3D;true signalisiert &#39;pending restart&#39;.
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param attachRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call attachAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull AttachRequest attachRequest, final ApiCallback<AttachmentDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = attachValidateBeforeCall(projectUuid, networkUuid, attachRequest, _callback);
        Type localVarReturnType = new TypeToken<AttachmentDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for create8
     * @param projectUuid  (required)
     * @param createRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call create8Call(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateRequest createRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createRequest;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/networks"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call create8ValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateRequest createRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling create8(Async)");
        }

        // verify the required parameter 'createRequest' is set
        if (createRequest == null) {
            throw new ApiException("Missing the required parameter 'createRequest' when calling create8(Async)");
        }

        return create8Call(projectUuid, createRequest, _callback);

    }

    /**
     * Ein Netzwerk anlegen
     * 
     * @param projectUuid  (required)
     * @param createRequest  (required)
     * @return TenantNetworkDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public TenantNetworkDto create8(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateRequest createRequest) throws ApiException {
        ApiResponse<TenantNetworkDto> localVarResp = create8WithHttpInfo(projectUuid, createRequest);
        return localVarResp.getData();
    }

    /**
     * Ein Netzwerk anlegen
     * 
     * @param projectUuid  (required)
     * @param createRequest  (required)
     * @return ApiResponse&lt;TenantNetworkDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TenantNetworkDto> create8WithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateRequest createRequest) throws ApiException {
        okhttp3.Call localVarCall = create8ValidateBeforeCall(projectUuid, createRequest, null);
        Type localVarReturnType = new TypeToken<TenantNetworkDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Ein Netzwerk anlegen (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param createRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call create8Async(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull CreateRequest createRequest, final ApiCallback<TenantNetworkDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = create8ValidateBeforeCall(projectUuid, createRequest, _callback);
        Type localVarReturnType = new TypeToken<TenantNetworkDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for delete9
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call delete9Call(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/networks/{networkUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "networkUuid" + "}", localVarApiClient.escapeString(networkUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call delete9ValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling delete9(Async)");
        }

        // verify the required parameter 'networkUuid' is set
        if (networkUuid == null) {
            throw new ApiException("Missing the required parameter 'networkUuid' when calling delete9(Async)");
        }

        return delete9Call(projectUuid, networkUuid, _callback);

    }

    /**
     * Ein Netzwerk loeschen
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public void delete9(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid) throws ApiException {
        delete9WithHttpInfo(projectUuid, networkUuid);
    }

    /**
     * Ein Netzwerk loeschen
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> delete9WithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid) throws ApiException {
        okhttp3.Call localVarCall = delete9ValidateBeforeCall(projectUuid, networkUuid, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Ein Netzwerk loeschen (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call delete9Async(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = delete9ValidateBeforeCall(projectUuid, networkUuid, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for detach
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param vmUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call detachCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull UUID vmUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/networks/{networkUuid}/attachments/{vmUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "networkUuid" + "}", localVarApiClient.escapeString(networkUuid.toString()))
            .replace("{" + "vmUuid" + "}", localVarApiClient.escapeString(vmUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call detachValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull UUID vmUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling detach(Async)");
        }

        // verify the required parameter 'networkUuid' is set
        if (networkUuid == null) {
            throw new ApiException("Missing the required parameter 'networkUuid' when calling detach(Async)");
        }

        // verify the required parameter 'vmUuid' is set
        if (vmUuid == null) {
            throw new ApiException("Missing the required parameter 'vmUuid' when calling detach(Async)");
        }

        return detachCall(projectUuid, networkUuid, vmUuid, _callback);

    }

    /**
     * Eine VM vom Netzwerk trennen
     * Idempotent (war-nicht-dran &#x3D;&#x3D; Erfolg). Das Secondary-Interface verschwindet erst beim VMI-Neustart → restartRequired spiegelt, ob sich etwas geaendert hat.
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param vmUuid  (required)
     * @return AttachmentDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public AttachmentDto detach(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull UUID vmUuid) throws ApiException {
        ApiResponse<AttachmentDto> localVarResp = detachWithHttpInfo(projectUuid, networkUuid, vmUuid);
        return localVarResp.getData();
    }

    /**
     * Eine VM vom Netzwerk trennen
     * Idempotent (war-nicht-dran &#x3D;&#x3D; Erfolg). Das Secondary-Interface verschwindet erst beim VMI-Neustart → restartRequired spiegelt, ob sich etwas geaendert hat.
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param vmUuid  (required)
     * @return ApiResponse&lt;AttachmentDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AttachmentDto> detachWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull UUID vmUuid) throws ApiException {
        okhttp3.Call localVarCall = detachValidateBeforeCall(projectUuid, networkUuid, vmUuid, null);
        Type localVarReturnType = new TypeToken<AttachmentDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Eine VM vom Netzwerk trennen (asynchronously)
     * Idempotent (war-nicht-dran &#x3D;&#x3D; Erfolg). Das Secondary-Interface verschwindet erst beim VMI-Neustart → restartRequired spiegelt, ob sich etwas geaendert hat.
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param vmUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call detachAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, @javax.annotation.Nonnull UUID vmUuid, final ApiCallback<AttachmentDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = detachValidateBeforeCall(projectUuid, networkUuid, vmUuid, _callback);
        Type localVarReturnType = new TypeToken<AttachmentDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for get7
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call get7Call(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/networks/{networkUuid}"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "networkUuid" + "}", localVarApiClient.escapeString(networkUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call get7ValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling get7(Async)");
        }

        // verify the required parameter 'networkUuid' is set
        if (networkUuid == null) {
            throw new ApiException("Missing the required parameter 'networkUuid' when calling get7(Async)");
        }

        return get7Call(projectUuid, networkUuid, _callback);

    }

    /**
     * Netzwerk-Details
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @return TenantNetworkDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public TenantNetworkDto get7(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid) throws ApiException {
        ApiResponse<TenantNetworkDto> localVarResp = get7WithHttpInfo(projectUuid, networkUuid);
        return localVarResp.getData();
    }

    /**
     * Netzwerk-Details
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @return ApiResponse&lt;TenantNetworkDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TenantNetworkDto> get7WithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid) throws ApiException {
        okhttp3.Call localVarCall = get7ValidateBeforeCall(projectUuid, networkUuid, null);
        Type localVarReturnType = new TypeToken<TenantNetworkDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Netzwerk-Details (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call get7Async(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback<TenantNetworkDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = get7ValidateBeforeCall(projectUuid, networkUuid, _callback);
        Type localVarReturnType = new TypeToken<TenantNetworkDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for list8
     * @param projectUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call list8Call(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/networks"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call list8ValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling list8(Async)");
        }

        return list8Call(projectUuid, _callback);

    }

    /**
     * Netzwerke des Projekts auflisten
     * 
     * @param projectUuid  (required)
     * @return List&lt;TenantNetworkDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<TenantNetworkDto> list8(@javax.annotation.Nonnull UUID projectUuid) throws ApiException {
        ApiResponse<List<TenantNetworkDto>> localVarResp = list8WithHttpInfo(projectUuid);
        return localVarResp.getData();
    }

    /**
     * Netzwerke des Projekts auflisten
     * 
     * @param projectUuid  (required)
     * @return ApiResponse&lt;List&lt;TenantNetworkDto&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<TenantNetworkDto>> list8WithHttpInfo(@javax.annotation.Nonnull UUID projectUuid) throws ApiException {
        okhttp3.Call localVarCall = list8ValidateBeforeCall(projectUuid, null);
        Type localVarReturnType = new TypeToken<List<TenantNetworkDto>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Netzwerke des Projekts auflisten (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call list8Async(@javax.annotation.Nonnull UUID projectUuid, final ApiCallback<List<TenantNetworkDto>> _callback) throws ApiException {

        okhttp3.Call localVarCall = list8ValidateBeforeCall(projectUuid, _callback);
        Type localVarReturnType = new TypeToken<List<TenantNetworkDto>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listAttachments
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listAttachmentsCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/projects/{projectUuid}/networks/{networkUuid}/attachments"
            .replace("{" + "projectUuid" + "}", localVarApiClient.escapeString(projectUuid.toString()))
            .replace("{" + "networkUuid" + "}", localVarApiClient.escapeString(networkUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listAttachmentsValidateBeforeCall(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'projectUuid' is set
        if (projectUuid == null) {
            throw new ApiException("Missing the required parameter 'projectUuid' when calling listAttachments(Async)");
        }

        // verify the required parameter 'networkUuid' is set
        if (networkUuid == null) {
            throw new ApiException("Missing the required parameter 'networkUuid' when calling listAttachments(Async)");
        }

        return listAttachmentsCall(projectUuid, networkUuid, _callback);

    }

    /**
     * Angehaengte VMs eines Netzwerks auflisten
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @return List&lt;UUID&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<UUID> listAttachments(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid) throws ApiException {
        ApiResponse<List<UUID>> localVarResp = listAttachmentsWithHttpInfo(projectUuid, networkUuid);
        return localVarResp.getData();
    }

    /**
     * Angehaengte VMs eines Netzwerks auflisten
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @return ApiResponse&lt;List&lt;UUID&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<UUID>> listAttachmentsWithHttpInfo(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid) throws ApiException {
        okhttp3.Call localVarCall = listAttachmentsValidateBeforeCall(projectUuid, networkUuid, null);
        Type localVarReturnType = new TypeToken<List<UUID>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Angehaengte VMs eines Netzwerks auflisten (asynchronously)
     * 
     * @param projectUuid  (required)
     * @param networkUuid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listAttachmentsAsync(@javax.annotation.Nonnull UUID projectUuid, @javax.annotation.Nonnull UUID networkUuid, final ApiCallback<List<UUID>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listAttachmentsValidateBeforeCall(projectUuid, networkUuid, _callback);
        Type localVarReturnType = new TypeToken<List<UUID>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
