/*
 * Darkstone Cloud API
 * REST API for the Darkstone Cloud platform: container compute, virtual machines, encrypted volumes, S3-compatible object storage, the vector database, AI inference, the DDoS-protected Cloud Gateway, billing and project management.  <a href=\"/oauth2/authorization/google\" style=\"display:inline-block;background:#4285F4;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;margin:8px 0;\">🔐 Sign in with Google</a>  After a successful login the session cookie is automatically attached to every Swagger request (same-origin). For non-browser clients, set an API key via the **Authorize** button in the top right (header `X-API-Key`, format `ds_…`). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@darkstone-entertainment.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PostalAddress;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BillingSetupRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T15:51:13.832251781Z[Etc/UTC]", comments = "Generator version: 7.24.0-SNAPSHOT")
public class BillingSetupRequest {
  /**
   * Gets or Sets customerType
   */
  @JsonAdapter(CustomerTypeEnum.Adapter.class)
  public enum CustomerTypeEnum {
    PRIVATE("PRIVATE"),
    
    BUSINESS("BUSINESS");

    private String value;

    CustomerTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CustomerTypeEnum fromValue(String value) {
      for (CustomerTypeEnum b : CustomerTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CustomerTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CustomerTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CustomerTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CustomerTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CustomerTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CUSTOMER_TYPE = "customerType";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_TYPE)
  @javax.annotation.Nullable
  private CustomerTypeEnum customerType;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  @javax.annotation.Nullable
  private String companyName;

  public static final String SERIALIZED_NAME_CONTACT_FIRST_NAME = "contactFirstName";
  @SerializedName(SERIALIZED_NAME_CONTACT_FIRST_NAME)
  @javax.annotation.Nullable
  private String contactFirstName;

  public static final String SERIALIZED_NAME_CONTACT_LAST_NAME = "contactLastName";
  @SerializedName(SERIALIZED_NAME_CONTACT_LAST_NAME)
  @javax.annotation.Nullable
  private String contactLastName;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private PostalAddress address;

  public BillingSetupRequest() {
  }

  public BillingSetupRequest customerType(@javax.annotation.Nullable CustomerTypeEnum customerType) {
    this.customerType = customerType;
    return this;
  }

  /**
   * Get customerType
   * @return customerType
   */
  @javax.annotation.Nullable
  public CustomerTypeEnum getCustomerType() {
    return customerType;
  }

  public void setCustomerType(@javax.annotation.Nullable CustomerTypeEnum customerType) {
    this.customerType = customerType;
  }


  public BillingSetupRequest companyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Get companyName
   * @return companyName
   */
  @javax.annotation.Nullable
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
  }


  public BillingSetupRequest contactFirstName(@javax.annotation.Nullable String contactFirstName) {
    this.contactFirstName = contactFirstName;
    return this;
  }

  /**
   * Get contactFirstName
   * @return contactFirstName
   */
  @javax.annotation.Nullable
  public String getContactFirstName() {
    return contactFirstName;
  }

  public void setContactFirstName(@javax.annotation.Nullable String contactFirstName) {
    this.contactFirstName = contactFirstName;
  }


  public BillingSetupRequest contactLastName(@javax.annotation.Nullable String contactLastName) {
    this.contactLastName = contactLastName;
    return this;
  }

  /**
   * Get contactLastName
   * @return contactLastName
   */
  @javax.annotation.Nullable
  public String getContactLastName() {
    return contactLastName;
  }

  public void setContactLastName(@javax.annotation.Nullable String contactLastName) {
    this.contactLastName = contactLastName;
  }


  public BillingSetupRequest address(@javax.annotation.Nullable PostalAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public PostalAddress getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable PostalAddress address) {
    this.address = address;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingSetupRequest billingSetupRequest = (BillingSetupRequest) o;
    return Objects.equals(this.customerType, billingSetupRequest.customerType) &&
        Objects.equals(this.companyName, billingSetupRequest.companyName) &&
        Objects.equals(this.contactFirstName, billingSetupRequest.contactFirstName) &&
        Objects.equals(this.contactLastName, billingSetupRequest.contactLastName) &&
        Objects.equals(this.address, billingSetupRequest.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerType, companyName, contactFirstName, contactLastName, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingSetupRequest {\n");
    sb.append("    customerType: ").append(toIndentedString(customerType)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    contactFirstName: ").append(toIndentedString(contactFirstName)).append("\n");
    sb.append("    contactLastName: ").append(toIndentedString(contactLastName)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("customerType", "companyName", "contactFirstName", "contactLastName", "address"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BillingSetupRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BillingSetupRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BillingSetupRequest is not found in the empty JSON string", BillingSetupRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BillingSetupRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BillingSetupRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("customerType") != null && !jsonObj.get("customerType").isJsonNull()) && !jsonObj.get("customerType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerType").toString()));
      }
      // validate the optional field `customerType`
      if (jsonObj.get("customerType") != null && !jsonObj.get("customerType").isJsonNull()) {
        CustomerTypeEnum.validateJsonElement(jsonObj.get("customerType"));
      }
      if ((jsonObj.get("companyName") != null && !jsonObj.get("companyName").isJsonNull()) && !jsonObj.get("companyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `companyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyName").toString()));
      }
      if ((jsonObj.get("contactFirstName") != null && !jsonObj.get("contactFirstName").isJsonNull()) && !jsonObj.get("contactFirstName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contactFirstName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactFirstName").toString()));
      }
      if ((jsonObj.get("contactLastName") != null && !jsonObj.get("contactLastName").isJsonNull()) && !jsonObj.get("contactLastName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contactLastName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactLastName").toString()));
      }
      // validate the optional field `address`
      if (jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) {
        PostalAddress.validateJsonElement(jsonObj.get("address"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BillingSetupRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BillingSetupRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BillingSetupRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BillingSetupRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<BillingSetupRequest>() {
           @Override
           public void write(JsonWriter out, BillingSetupRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BillingSetupRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BillingSetupRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BillingSetupRequest
   * @throws IOException if the JSON string is invalid with respect to BillingSetupRequest
   */
  public static BillingSetupRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BillingSetupRequest.class);
  }

  /**
   * Convert an instance of BillingSetupRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

