/*
 * Darkstone Cloud API
 * REST API for the Darkstone Cloud platform: container compute, virtual machines, encrypted volumes, S3-compatible object storage, the vector database, AI inference, the DDoS-protected Cloud Gateway, billing and project management.  <a href=\"/oauth2/authorization/google\" style=\"display:inline-block;background:#4285F4;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;margin:8px 0;\">🔐 Sign in with Google</a>  After a successful login the session cookie is automatically attached to every Swagger request (same-origin). For non-browser clients, set an API key via the **Authorize** button in the top right (header `X-API-Key`, format `ds_…`). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@darkstone-entertainment.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateVolumeRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T15:51:13.832251781Z[Etc/UTC]", comments = "Generator version: 7.24.0-SNAPSHOT")
public class CreateVolumeRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_CAPACITY_BYTES = "capacityBytes";
  @SerializedName(SERIALIZED_NAME_CAPACITY_BYTES)
  @javax.annotation.Nullable
  private Long capacityBytes;

  public static final String SERIALIZED_NAME_PRIMARY_SITE = "primarySite";
  @SerializedName(SERIALIZED_NAME_PRIMARY_SITE)
  @javax.annotation.Nullable
  private String primarySite;

  public static final String SERIALIZED_NAME_MIRROR_SITES = "mirrorSites";
  @SerializedName(SERIALIZED_NAME_MIRROR_SITES)
  @javax.annotation.Nullable
  private List<String> mirrorSites = new ArrayList<>();

  public static final String SERIALIZED_NAME_ENCRYPTION_CREDENTIAL_UUID = "encryptionCredentialUuid";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION_CREDENTIAL_UUID)
  @javax.annotation.Nullable
  private UUID encryptionCredentialUuid;

  public static final String SERIALIZED_NAME_BYOK_KEY_BASE64 = "byokKeyBase64";
  @SerializedName(SERIALIZED_NAME_BYOK_KEY_BASE64)
  @javax.annotation.Nullable
  private String byokKeyBase64;

  public static final String SERIALIZED_NAME_ENCRYPTION_KEY_NAME = "encryptionKeyName";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION_KEY_NAME)
  @javax.annotation.Nullable
  private String encryptionKeyName;

  /**
   * Gets or Sets billingMode
   */
  @JsonAdapter(BillingModeEnum.Adapter.class)
  public enum BillingModeEnum {
    PER_MINUTE("PER_MINUTE"),
    
    PER_DAY("PER_DAY");

    private String value;

    BillingModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BillingModeEnum fromValue(String value) {
      for (BillingModeEnum b : BillingModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BillingModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BillingModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BillingModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BillingModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BillingModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BILLING_MODE = "billingMode";
  @SerializedName(SERIALIZED_NAME_BILLING_MODE)
  @javax.annotation.Nullable
  private BillingModeEnum billingMode;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  @javax.annotation.Nullable
  private String region;

  public CreateVolumeRequest() {
  }

  public CreateVolumeRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateVolumeRequest capacityBytes(@javax.annotation.Nullable Long capacityBytes) {
    this.capacityBytes = capacityBytes;
    return this;
  }

  /**
   * Get capacityBytes
   * @return capacityBytes
   */
  @javax.annotation.Nullable
  public Long getCapacityBytes() {
    return capacityBytes;
  }

  public void setCapacityBytes(@javax.annotation.Nullable Long capacityBytes) {
    this.capacityBytes = capacityBytes;
  }


  public CreateVolumeRequest primarySite(@javax.annotation.Nullable String primarySite) {
    this.primarySite = primarySite;
    return this;
  }

  /**
   * Get primarySite
   * @return primarySite
   */
  @javax.annotation.Nullable
  public String getPrimarySite() {
    return primarySite;
  }

  public void setPrimarySite(@javax.annotation.Nullable String primarySite) {
    this.primarySite = primarySite;
  }


  public CreateVolumeRequest mirrorSites(@javax.annotation.Nullable List<String> mirrorSites) {
    this.mirrorSites = mirrorSites;
    return this;
  }

  public CreateVolumeRequest addMirrorSitesItem(String mirrorSitesItem) {
    if (this.mirrorSites == null) {
      this.mirrorSites = new ArrayList<>();
    }
    this.mirrorSites.add(mirrorSitesItem);
    return this;
  }

  /**
   * Get mirrorSites
   * @return mirrorSites
   */
  @javax.annotation.Nullable
  public List<String> getMirrorSites() {
    return mirrorSites;
  }

  public void setMirrorSites(@javax.annotation.Nullable List<String> mirrorSites) {
    this.mirrorSites = mirrorSites;
  }


  public CreateVolumeRequest encryptionCredentialUuid(@javax.annotation.Nullable UUID encryptionCredentialUuid) {
    this.encryptionCredentialUuid = encryptionCredentialUuid;
    return this;
  }

  /**
   * Get encryptionCredentialUuid
   * @return encryptionCredentialUuid
   */
  @javax.annotation.Nullable
  public UUID getEncryptionCredentialUuid() {
    return encryptionCredentialUuid;
  }

  public void setEncryptionCredentialUuid(@javax.annotation.Nullable UUID encryptionCredentialUuid) {
    this.encryptionCredentialUuid = encryptionCredentialUuid;
  }


  public CreateVolumeRequest byokKeyBase64(@javax.annotation.Nullable String byokKeyBase64) {
    this.byokKeyBase64 = byokKeyBase64;
    return this;
  }

  /**
   * Get byokKeyBase64
   * @return byokKeyBase64
   */
  @javax.annotation.Nullable
  public String getByokKeyBase64() {
    return byokKeyBase64;
  }

  public void setByokKeyBase64(@javax.annotation.Nullable String byokKeyBase64) {
    this.byokKeyBase64 = byokKeyBase64;
  }


  public CreateVolumeRequest encryptionKeyName(@javax.annotation.Nullable String encryptionKeyName) {
    this.encryptionKeyName = encryptionKeyName;
    return this;
  }

  /**
   * Get encryptionKeyName
   * @return encryptionKeyName
   */
  @javax.annotation.Nullable
  public String getEncryptionKeyName() {
    return encryptionKeyName;
  }

  public void setEncryptionKeyName(@javax.annotation.Nullable String encryptionKeyName) {
    this.encryptionKeyName = encryptionKeyName;
  }


  public CreateVolumeRequest billingMode(@javax.annotation.Nullable BillingModeEnum billingMode) {
    this.billingMode = billingMode;
    return this;
  }

  /**
   * Get billingMode
   * @return billingMode
   */
  @javax.annotation.Nullable
  public BillingModeEnum getBillingMode() {
    return billingMode;
  }

  public void setBillingMode(@javax.annotation.Nullable BillingModeEnum billingMode) {
    this.billingMode = billingMode;
  }


  public CreateVolumeRequest region(@javax.annotation.Nullable String region) {
    this.region = region;
    return this;
  }

  /**
   * Get region
   * @return region
   */
  @javax.annotation.Nullable
  public String getRegion() {
    return region;
  }

  public void setRegion(@javax.annotation.Nullable String region) {
    this.region = region;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVolumeRequest createVolumeRequest = (CreateVolumeRequest) o;
    return Objects.equals(this.name, createVolumeRequest.name) &&
        Objects.equals(this.capacityBytes, createVolumeRequest.capacityBytes) &&
        Objects.equals(this.primarySite, createVolumeRequest.primarySite) &&
        Objects.equals(this.mirrorSites, createVolumeRequest.mirrorSites) &&
        Objects.equals(this.encryptionCredentialUuid, createVolumeRequest.encryptionCredentialUuid) &&
        Objects.equals(this.byokKeyBase64, createVolumeRequest.byokKeyBase64) &&
        Objects.equals(this.encryptionKeyName, createVolumeRequest.encryptionKeyName) &&
        Objects.equals(this.billingMode, createVolumeRequest.billingMode) &&
        Objects.equals(this.region, createVolumeRequest.region);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, capacityBytes, primarySite, mirrorSites, encryptionCredentialUuid, byokKeyBase64, encryptionKeyName, billingMode, region);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVolumeRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    capacityBytes: ").append(toIndentedString(capacityBytes)).append("\n");
    sb.append("    primarySite: ").append(toIndentedString(primarySite)).append("\n");
    sb.append("    mirrorSites: ").append(toIndentedString(mirrorSites)).append("\n");
    sb.append("    encryptionCredentialUuid: ").append(toIndentedString(encryptionCredentialUuid)).append("\n");
    sb.append("    byokKeyBase64: ").append(toIndentedString(byokKeyBase64)).append("\n");
    sb.append("    encryptionKeyName: ").append(toIndentedString(encryptionKeyName)).append("\n");
    sb.append("    billingMode: ").append(toIndentedString(billingMode)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "capacityBytes", "primarySite", "mirrorSites", "encryptionCredentialUuid", "byokKeyBase64", "encryptionKeyName", "billingMode", "region"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateVolumeRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateVolumeRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateVolumeRequest is not found in the empty JSON string", CreateVolumeRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateVolumeRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateVolumeRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("primarySite") != null && !jsonObj.get("primarySite").isJsonNull()) && !jsonObj.get("primarySite").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `primarySite` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primarySite").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("mirrorSites") != null && !jsonObj.get("mirrorSites").isJsonNull() && !jsonObj.get("mirrorSites").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mirrorSites` to be an array in the JSON string but got `%s`", jsonObj.get("mirrorSites").toString()));
      }
      if ((jsonObj.get("encryptionCredentialUuid") != null && !jsonObj.get("encryptionCredentialUuid").isJsonNull()) && !jsonObj.get("encryptionCredentialUuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `encryptionCredentialUuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("encryptionCredentialUuid").toString()));
      }
      if ((jsonObj.get("byokKeyBase64") != null && !jsonObj.get("byokKeyBase64").isJsonNull()) && !jsonObj.get("byokKeyBase64").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `byokKeyBase64` to be a primitive type in the JSON string but got `%s`", jsonObj.get("byokKeyBase64").toString()));
      }
      if ((jsonObj.get("encryptionKeyName") != null && !jsonObj.get("encryptionKeyName").isJsonNull()) && !jsonObj.get("encryptionKeyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `encryptionKeyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("encryptionKeyName").toString()));
      }
      if ((jsonObj.get("billingMode") != null && !jsonObj.get("billingMode").isJsonNull()) && !jsonObj.get("billingMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `billingMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billingMode").toString()));
      }
      // validate the optional field `billingMode`
      if (jsonObj.get("billingMode") != null && !jsonObj.get("billingMode").isJsonNull()) {
        BillingModeEnum.validateJsonElement(jsonObj.get("billingMode"));
      }
      if ((jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull()) && !jsonObj.get("region").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateVolumeRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateVolumeRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateVolumeRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateVolumeRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateVolumeRequest>() {
           @Override
           public void write(JsonWriter out, CreateVolumeRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateVolumeRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateVolumeRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateVolumeRequest
   * @throws IOException if the JSON string is invalid with respect to CreateVolumeRequest
   */
  public static CreateVolumeRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateVolumeRequest.class);
  }

  /**
   * Convert an instance of CreateVolumeRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

