/*
 * Darkstone Cloud API
 * REST API for the Darkstone Cloud platform: container compute, virtual machines, encrypted volumes, S3-compatible object storage, the vector database, AI inference, the DDoS-protected Cloud Gateway, billing and project management.  <a href=\"/oauth2/authorization/google\" style=\"display:inline-block;background:#4285F4;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;margin:8px 0;\">🔐 Sign in with Google</a>  After a successful login the session cookie is automatically attached to every Swagger request (same-origin). For non-browser clients, set an API key via the **Authorize** button in the top right (header `X-API-Key`, format `ds_…`). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@darkstone-entertainment.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GatewayDtoV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T15:51:13.832251781Z[Etc/UTC]", comments = "Generator version: 7.24.0-SNAPSHOT")
public class GatewayDtoV2 {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  @javax.annotation.Nullable
  private UUID uuid;

  public static final String SERIALIZED_NAME_PROJECT_UUID = "projectUuid";
  @SerializedName(SERIALIZED_NAME_PROJECT_UUID)
  @javax.annotation.Nullable
  private UUID projectUuid;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @javax.annotation.Nullable
  private String size;

  public static final String SERIALIZED_NAME_PENDING_SIZE = "pendingSize";
  @SerializedName(SERIALIZED_NAME_PENDING_SIZE)
  @javax.annotation.Nullable
  private String pendingSize;

  public static final String SERIALIZED_NAME_REGIONS = "regions";
  @SerializedName(SERIALIZED_NAME_REGIONS)
  @javax.annotation.Nullable
  private List<String> regions = new ArrayList<>();

  public static final String SERIALIZED_NAME_IP_COUNT_TARGET = "ipCountTarget";
  @SerializedName(SERIALIZED_NAME_IP_COUNT_TARGET)
  @javax.annotation.Nullable
  private Integer ipCountTarget;

  public static final String SERIALIZED_NAME_IP_COUNT_ASSIGNED = "ipCountAssigned";
  @SerializedName(SERIALIZED_NAME_IP_COUNT_ASSIGNED)
  @javax.annotation.Nullable
  private Integer ipCountAssigned;

  public static final String SERIALIZED_NAME_MONTHLY_PRICE_EUR = "monthlyPriceEur";
  @SerializedName(SERIALIZED_NAME_MONTHLY_PRICE_EUR)
  @javax.annotation.Nullable
  private BigDecimal monthlyPriceEur;

  public static final String SERIALIZED_NAME_NEXT_RENEWAL_AT = "nextRenewalAt";
  @SerializedName(SERIALIZED_NAME_NEXT_RENEWAL_AT)
  @javax.annotation.Nullable
  private OffsetDateTime nextRenewalAt;

  public static final String SERIALIZED_NAME_SERVICE_SUSPENDED = "serviceSuspended";
  @SerializedName(SERIALIZED_NAME_SERVICE_SUSPENDED)
  @javax.annotation.Nullable
  private Boolean serviceSuspended;

  public static final String SERIALIZED_NAME_SUBDOMAIN_SLUG = "subdomainSlug";
  @SerializedName(SERIALIZED_NAME_SUBDOMAIN_SLUG)
  @javax.annotation.Nullable
  private String subdomainSlug;

  public static final String SERIALIZED_NAME_FQDN = "fqdn";
  @SerializedName(SERIALIZED_NAME_FQDN)
  @javax.annotation.Nullable
  private String fqdn;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public GatewayDtoV2() {
  }

  public GatewayDtoV2 uuid(@javax.annotation.Nullable UUID uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * Get uuid
   * @return uuid
   */
  @javax.annotation.Nullable
  public UUID getUuid() {
    return uuid;
  }

  public void setUuid(@javax.annotation.Nullable UUID uuid) {
    this.uuid = uuid;
  }


  public GatewayDtoV2 projectUuid(@javax.annotation.Nullable UUID projectUuid) {
    this.projectUuid = projectUuid;
    return this;
  }

  /**
   * Get projectUuid
   * @return projectUuid
   */
  @javax.annotation.Nullable
  public UUID getProjectUuid() {
    return projectUuid;
  }

  public void setProjectUuid(@javax.annotation.Nullable UUID projectUuid) {
    this.projectUuid = projectUuid;
  }


  public GatewayDtoV2 name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public GatewayDtoV2 type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public GatewayDtoV2 size(@javax.annotation.Nullable String size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   * @return size
   */
  @javax.annotation.Nullable
  public String getSize() {
    return size;
  }

  public void setSize(@javax.annotation.Nullable String size) {
    this.size = size;
  }


  public GatewayDtoV2 pendingSize(@javax.annotation.Nullable String pendingSize) {
    this.pendingSize = pendingSize;
    return this;
  }

  /**
   * Get pendingSize
   * @return pendingSize
   */
  @javax.annotation.Nullable
  public String getPendingSize() {
    return pendingSize;
  }

  public void setPendingSize(@javax.annotation.Nullable String pendingSize) {
    this.pendingSize = pendingSize;
  }


  public GatewayDtoV2 regions(@javax.annotation.Nullable List<String> regions) {
    this.regions = regions;
    return this;
  }

  public GatewayDtoV2 addRegionsItem(String regionsItem) {
    if (this.regions == null) {
      this.regions = new ArrayList<>();
    }
    this.regions.add(regionsItem);
    return this;
  }

  /**
   * Get regions
   * @return regions
   */
  @javax.annotation.Nullable
  public List<String> getRegions() {
    return regions;
  }

  public void setRegions(@javax.annotation.Nullable List<String> regions) {
    this.regions = regions;
  }


  public GatewayDtoV2 ipCountTarget(@javax.annotation.Nullable Integer ipCountTarget) {
    this.ipCountTarget = ipCountTarget;
    return this;
  }

  /**
   * Get ipCountTarget
   * @return ipCountTarget
   */
  @javax.annotation.Nullable
  public Integer getIpCountTarget() {
    return ipCountTarget;
  }

  public void setIpCountTarget(@javax.annotation.Nullable Integer ipCountTarget) {
    this.ipCountTarget = ipCountTarget;
  }


  public GatewayDtoV2 ipCountAssigned(@javax.annotation.Nullable Integer ipCountAssigned) {
    this.ipCountAssigned = ipCountAssigned;
    return this;
  }

  /**
   * Get ipCountAssigned
   * @return ipCountAssigned
   */
  @javax.annotation.Nullable
  public Integer getIpCountAssigned() {
    return ipCountAssigned;
  }

  public void setIpCountAssigned(@javax.annotation.Nullable Integer ipCountAssigned) {
    this.ipCountAssigned = ipCountAssigned;
  }


  public GatewayDtoV2 monthlyPriceEur(@javax.annotation.Nullable BigDecimal monthlyPriceEur) {
    this.monthlyPriceEur = monthlyPriceEur;
    return this;
  }

  /**
   * Get monthlyPriceEur
   * @return monthlyPriceEur
   */
  @javax.annotation.Nullable
  public BigDecimal getMonthlyPriceEur() {
    return monthlyPriceEur;
  }

  public void setMonthlyPriceEur(@javax.annotation.Nullable BigDecimal monthlyPriceEur) {
    this.monthlyPriceEur = monthlyPriceEur;
  }


  public GatewayDtoV2 nextRenewalAt(@javax.annotation.Nullable OffsetDateTime nextRenewalAt) {
    this.nextRenewalAt = nextRenewalAt;
    return this;
  }

  /**
   * Get nextRenewalAt
   * @return nextRenewalAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getNextRenewalAt() {
    return nextRenewalAt;
  }

  public void setNextRenewalAt(@javax.annotation.Nullable OffsetDateTime nextRenewalAt) {
    this.nextRenewalAt = nextRenewalAt;
  }


  public GatewayDtoV2 serviceSuspended(@javax.annotation.Nullable Boolean serviceSuspended) {
    this.serviceSuspended = serviceSuspended;
    return this;
  }

  /**
   * Get serviceSuspended
   * @return serviceSuspended
   */
  @javax.annotation.Nullable
  public Boolean getServiceSuspended() {
    return serviceSuspended;
  }

  public void setServiceSuspended(@javax.annotation.Nullable Boolean serviceSuspended) {
    this.serviceSuspended = serviceSuspended;
  }


  public GatewayDtoV2 subdomainSlug(@javax.annotation.Nullable String subdomainSlug) {
    this.subdomainSlug = subdomainSlug;
    return this;
  }

  /**
   * Get subdomainSlug
   * @return subdomainSlug
   */
  @javax.annotation.Nullable
  public String getSubdomainSlug() {
    return subdomainSlug;
  }

  public void setSubdomainSlug(@javax.annotation.Nullable String subdomainSlug) {
    this.subdomainSlug = subdomainSlug;
  }


  public GatewayDtoV2 fqdn(@javax.annotation.Nullable String fqdn) {
    this.fqdn = fqdn;
    return this;
  }

  /**
   * Get fqdn
   * @return fqdn
   */
  @javax.annotation.Nullable
  public String getFqdn() {
    return fqdn;
  }

  public void setFqdn(@javax.annotation.Nullable String fqdn) {
    this.fqdn = fqdn;
  }


  public GatewayDtoV2 status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GatewayDtoV2 gatewayDtoV2 = (GatewayDtoV2) o;
    return Objects.equals(this.uuid, gatewayDtoV2.uuid) &&
        Objects.equals(this.projectUuid, gatewayDtoV2.projectUuid) &&
        Objects.equals(this.name, gatewayDtoV2.name) &&
        Objects.equals(this.type, gatewayDtoV2.type) &&
        Objects.equals(this.size, gatewayDtoV2.size) &&
        Objects.equals(this.pendingSize, gatewayDtoV2.pendingSize) &&
        Objects.equals(this.regions, gatewayDtoV2.regions) &&
        Objects.equals(this.ipCountTarget, gatewayDtoV2.ipCountTarget) &&
        Objects.equals(this.ipCountAssigned, gatewayDtoV2.ipCountAssigned) &&
        Objects.equals(this.monthlyPriceEur, gatewayDtoV2.monthlyPriceEur) &&
        Objects.equals(this.nextRenewalAt, gatewayDtoV2.nextRenewalAt) &&
        Objects.equals(this.serviceSuspended, gatewayDtoV2.serviceSuspended) &&
        Objects.equals(this.subdomainSlug, gatewayDtoV2.subdomainSlug) &&
        Objects.equals(this.fqdn, gatewayDtoV2.fqdn) &&
        Objects.equals(this.status, gatewayDtoV2.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, projectUuid, name, type, size, pendingSize, regions, ipCountTarget, ipCountAssigned, monthlyPriceEur, nextRenewalAt, serviceSuspended, subdomainSlug, fqdn, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GatewayDtoV2 {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    projectUuid: ").append(toIndentedString(projectUuid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    pendingSize: ").append(toIndentedString(pendingSize)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    ipCountTarget: ").append(toIndentedString(ipCountTarget)).append("\n");
    sb.append("    ipCountAssigned: ").append(toIndentedString(ipCountAssigned)).append("\n");
    sb.append("    monthlyPriceEur: ").append(toIndentedString(monthlyPriceEur)).append("\n");
    sb.append("    nextRenewalAt: ").append(toIndentedString(nextRenewalAt)).append("\n");
    sb.append("    serviceSuspended: ").append(toIndentedString(serviceSuspended)).append("\n");
    sb.append("    subdomainSlug: ").append(toIndentedString(subdomainSlug)).append("\n");
    sb.append("    fqdn: ").append(toIndentedString(fqdn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("uuid", "projectUuid", "name", "type", "size", "pendingSize", "regions", "ipCountTarget", "ipCountAssigned", "monthlyPriceEur", "nextRenewalAt", "serviceSuspended", "subdomainSlug", "fqdn", "status"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GatewayDtoV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GatewayDtoV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GatewayDtoV2 is not found in the empty JSON string", GatewayDtoV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GatewayDtoV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GatewayDtoV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("uuid") != null && !jsonObj.get("uuid").isJsonNull()) && !jsonObj.get("uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid").toString()));
      }
      if ((jsonObj.get("projectUuid") != null && !jsonObj.get("projectUuid").isJsonNull()) && !jsonObj.get("projectUuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `projectUuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("projectUuid").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("size") != null && !jsonObj.get("size").isJsonNull()) && !jsonObj.get("size").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `size` to be a primitive type in the JSON string but got `%s`", jsonObj.get("size").toString()));
      }
      if ((jsonObj.get("pendingSize") != null && !jsonObj.get("pendingSize").isJsonNull()) && !jsonObj.get("pendingSize").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pendingSize` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pendingSize").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("regions") != null && !jsonObj.get("regions").isJsonNull() && !jsonObj.get("regions").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `regions` to be an array in the JSON string but got `%s`", jsonObj.get("regions").toString()));
      }
      if ((jsonObj.get("subdomainSlug") != null && !jsonObj.get("subdomainSlug").isJsonNull()) && !jsonObj.get("subdomainSlug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subdomainSlug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subdomainSlug").toString()));
      }
      if ((jsonObj.get("fqdn") != null && !jsonObj.get("fqdn").isJsonNull()) && !jsonObj.get("fqdn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fqdn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fqdn").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GatewayDtoV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GatewayDtoV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GatewayDtoV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GatewayDtoV2.class));

       return (TypeAdapter<T>) new TypeAdapter<GatewayDtoV2>() {
           @Override
           public void write(JsonWriter out, GatewayDtoV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GatewayDtoV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GatewayDtoV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GatewayDtoV2
   * @throws IOException if the JSON string is invalid with respect to GatewayDtoV2
   */
  public static GatewayDtoV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GatewayDtoV2.class);
  }

  /**
   * Convert an instance of GatewayDtoV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

