/*
 * Darkstone Cloud API
 * REST API for the Darkstone Cloud platform: container compute, virtual machines, encrypted volumes, S3-compatible object storage, the vector database, AI inference, the DDoS-protected Cloud Gateway, billing and project management.  <a href=\"/oauth2/authorization/google\" style=\"display:inline-block;background:#4285F4;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;margin:8px 0;\">🔐 Sign in with Google</a>  After a successful login the session cookie is automatically attached to every Swagger request (same-origin). For non-browser clients, set an API key via the **Authorize** button in the top right (header `X-API-Key`, format `ds_…`). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@darkstone-entertainment.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SamplePoint
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T15:51:13.832251781Z[Etc/UTC]", comments = "Generator version: 7.24.0-SNAPSHOT")
public class SamplePoint {
  public static final String SERIALIZED_NAME_AT = "at";
  @SerializedName(SERIALIZED_NAME_AT)
  @javax.annotation.Nullable
  private OffsetDateTime at;

  public static final String SERIALIZED_NAME_CPU_MILLI_CORES = "cpuMilliCores";
  @SerializedName(SERIALIZED_NAME_CPU_MILLI_CORES)
  @javax.annotation.Nullable
  private Long cpuMilliCores;

  public static final String SERIALIZED_NAME_MEMORY_BYTES = "memoryBytes";
  @SerializedName(SERIALIZED_NAME_MEMORY_BYTES)
  @javax.annotation.Nullable
  private Long memoryBytes;

  public static final String SERIALIZED_NAME_NET_RX_BYTES_PER_SEC = "netRxBytesPerSec";
  @SerializedName(SERIALIZED_NAME_NET_RX_BYTES_PER_SEC)
  @javax.annotation.Nullable
  private Long netRxBytesPerSec;

  public static final String SERIALIZED_NAME_NET_TX_BYTES_PER_SEC = "netTxBytesPerSec";
  @SerializedName(SERIALIZED_NAME_NET_TX_BYTES_PER_SEC)
  @javax.annotation.Nullable
  private Long netTxBytesPerSec;

  public static final String SERIALIZED_NAME_DISK_READ_BYTES_PER_SEC = "diskReadBytesPerSec";
  @SerializedName(SERIALIZED_NAME_DISK_READ_BYTES_PER_SEC)
  @javax.annotation.Nullable
  private Long diskReadBytesPerSec;

  public static final String SERIALIZED_NAME_DISK_WRITE_BYTES_PER_SEC = "diskWriteBytesPerSec";
  @SerializedName(SERIALIZED_NAME_DISK_WRITE_BYTES_PER_SEC)
  @javax.annotation.Nullable
  private Long diskWriteBytesPerSec;

  public SamplePoint() {
  }

  public SamplePoint at(@javax.annotation.Nullable OffsetDateTime at) {
    this.at = at;
    return this;
  }

  /**
   * Get at
   * @return at
   */
  @javax.annotation.Nullable
  public OffsetDateTime getAt() {
    return at;
  }

  public void setAt(@javax.annotation.Nullable OffsetDateTime at) {
    this.at = at;
  }


  public SamplePoint cpuMilliCores(@javax.annotation.Nullable Long cpuMilliCores) {
    this.cpuMilliCores = cpuMilliCores;
    return this;
  }

  /**
   * Get cpuMilliCores
   * @return cpuMilliCores
   */
  @javax.annotation.Nullable
  public Long getCpuMilliCores() {
    return cpuMilliCores;
  }

  public void setCpuMilliCores(@javax.annotation.Nullable Long cpuMilliCores) {
    this.cpuMilliCores = cpuMilliCores;
  }


  public SamplePoint memoryBytes(@javax.annotation.Nullable Long memoryBytes) {
    this.memoryBytes = memoryBytes;
    return this;
  }

  /**
   * Get memoryBytes
   * @return memoryBytes
   */
  @javax.annotation.Nullable
  public Long getMemoryBytes() {
    return memoryBytes;
  }

  public void setMemoryBytes(@javax.annotation.Nullable Long memoryBytes) {
    this.memoryBytes = memoryBytes;
  }


  public SamplePoint netRxBytesPerSec(@javax.annotation.Nullable Long netRxBytesPerSec) {
    this.netRxBytesPerSec = netRxBytesPerSec;
    return this;
  }

  /**
   * Get netRxBytesPerSec
   * @return netRxBytesPerSec
   */
  @javax.annotation.Nullable
  public Long getNetRxBytesPerSec() {
    return netRxBytesPerSec;
  }

  public void setNetRxBytesPerSec(@javax.annotation.Nullable Long netRxBytesPerSec) {
    this.netRxBytesPerSec = netRxBytesPerSec;
  }


  public SamplePoint netTxBytesPerSec(@javax.annotation.Nullable Long netTxBytesPerSec) {
    this.netTxBytesPerSec = netTxBytesPerSec;
    return this;
  }

  /**
   * Get netTxBytesPerSec
   * @return netTxBytesPerSec
   */
  @javax.annotation.Nullable
  public Long getNetTxBytesPerSec() {
    return netTxBytesPerSec;
  }

  public void setNetTxBytesPerSec(@javax.annotation.Nullable Long netTxBytesPerSec) {
    this.netTxBytesPerSec = netTxBytesPerSec;
  }


  public SamplePoint diskReadBytesPerSec(@javax.annotation.Nullable Long diskReadBytesPerSec) {
    this.diskReadBytesPerSec = diskReadBytesPerSec;
    return this;
  }

  /**
   * Get diskReadBytesPerSec
   * @return diskReadBytesPerSec
   */
  @javax.annotation.Nullable
  public Long getDiskReadBytesPerSec() {
    return diskReadBytesPerSec;
  }

  public void setDiskReadBytesPerSec(@javax.annotation.Nullable Long diskReadBytesPerSec) {
    this.diskReadBytesPerSec = diskReadBytesPerSec;
  }


  public SamplePoint diskWriteBytesPerSec(@javax.annotation.Nullable Long diskWriteBytesPerSec) {
    this.diskWriteBytesPerSec = diskWriteBytesPerSec;
    return this;
  }

  /**
   * Get diskWriteBytesPerSec
   * @return diskWriteBytesPerSec
   */
  @javax.annotation.Nullable
  public Long getDiskWriteBytesPerSec() {
    return diskWriteBytesPerSec;
  }

  public void setDiskWriteBytesPerSec(@javax.annotation.Nullable Long diskWriteBytesPerSec) {
    this.diskWriteBytesPerSec = diskWriteBytesPerSec;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SamplePoint samplePoint = (SamplePoint) o;
    return Objects.equals(this.at, samplePoint.at) &&
        Objects.equals(this.cpuMilliCores, samplePoint.cpuMilliCores) &&
        Objects.equals(this.memoryBytes, samplePoint.memoryBytes) &&
        Objects.equals(this.netRxBytesPerSec, samplePoint.netRxBytesPerSec) &&
        Objects.equals(this.netTxBytesPerSec, samplePoint.netTxBytesPerSec) &&
        Objects.equals(this.diskReadBytesPerSec, samplePoint.diskReadBytesPerSec) &&
        Objects.equals(this.diskWriteBytesPerSec, samplePoint.diskWriteBytesPerSec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(at, cpuMilliCores, memoryBytes, netRxBytesPerSec, netTxBytesPerSec, diskReadBytesPerSec, diskWriteBytesPerSec);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SamplePoint {\n");
    sb.append("    at: ").append(toIndentedString(at)).append("\n");
    sb.append("    cpuMilliCores: ").append(toIndentedString(cpuMilliCores)).append("\n");
    sb.append("    memoryBytes: ").append(toIndentedString(memoryBytes)).append("\n");
    sb.append("    netRxBytesPerSec: ").append(toIndentedString(netRxBytesPerSec)).append("\n");
    sb.append("    netTxBytesPerSec: ").append(toIndentedString(netTxBytesPerSec)).append("\n");
    sb.append("    diskReadBytesPerSec: ").append(toIndentedString(diskReadBytesPerSec)).append("\n");
    sb.append("    diskWriteBytesPerSec: ").append(toIndentedString(diskWriteBytesPerSec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("at", "cpuMilliCores", "memoryBytes", "netRxBytesPerSec", "netTxBytesPerSec", "diskReadBytesPerSec", "diskWriteBytesPerSec"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SamplePoint
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SamplePoint.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SamplePoint is not found in the empty JSON string", SamplePoint.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SamplePoint.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SamplePoint` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SamplePoint.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SamplePoint' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SamplePoint> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SamplePoint.class));

       return (TypeAdapter<T>) new TypeAdapter<SamplePoint>() {
           @Override
           public void write(JsonWriter out, SamplePoint value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SamplePoint read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SamplePoint given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SamplePoint
   * @throws IOException if the JSON string is invalid with respect to SamplePoint
   */
  public static SamplePoint fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SamplePoint.class);
  }

  /**
   * Convert an instance of SamplePoint to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

