name: Hourly API Sync
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v ${{ github.workspace }}:/local openapitools/openapi-generator-cli generate \
            -i https://api.darkstone.de/v3/api-docs \
            -g java \
            -o /local \
            --skip-validate-spec \
            --global-property apiTests=false,modelTests=false,apiDocs=false,modelDocs=false,supportingFiles=false \
            --additional-properties=library=native
      - run: |
          git config user.name "bot"
          git config user.email "bot@darkstone.de"
          git add .
          git commit -m "chore(api): auto-update" && git push || true
